// بيانات المؤشرات الكاملة
const indicatorsData = [
    {
        code: "EC-01",
        name: "معدل فروع المصارف التجارية لكل 100,000 شخص بالغ و (ب) عدد أجهزة الصرف الآلي لكل 100,000 شخص بالغ",
        definition: "عدد فروع المصارف التجارية لكل، 100,000 شخص بالغ وعدد أجهزة الصرف الآلي لكل 100,000 شخص بالغ",
        calculationMethod: "عدد فروع المصارف التجارية لكل 100,000 شخص بالغ في السنة = (عدد المصارف التجارية / عدد السكان البالغين في نفس السنة) * 100,000<br>عدد أجهزة الصرف الآلي لكل 100,000 شخص بالغ في السنة = (عدد أجهزة الصرف الآلي / عدد السكان البالغين في نفس السنة) * 100,000",
        unit: "عدد",
        references: "أهداف التنمية المستدامة (SDGs)",
        dataSource: "نشرة إحصاءات الخدمات والبنك المركزي 2023م",
        dataSourceType: "بيانات متاحة",
        geographicalScope: "منطقة",
        productionStatus: "تم الإنتاج",
        rating: "☆☆☆☆☆",
        notes: "",
        englishName: "(a) Number of commercial bank branches per 100,000 adults and (b) Number of ATMs per 100,000 adults",
        sector: "التنمية الإقتصادية"
    },
    {
        code: "EC-03",
        name: "معدل التضخم",
        definition: "يقيس التضخم الزيادة في أسعار مجموعات السلع والخدمات خلال فترة زمنية معينة، وعادة ما تكون سنة واحدة. وعكس التضخم هو الانكماش، والذي يحدث عندما تزداد القوة الشرائية للنقود وتنخفض الأسعار.",
        calculationMethod: "(الرقم القياسي للأسعار للسنة أو الفترة الحالية - الرقم القياسي للأسعار للسنة أو الفترة السابقة) ÷ الرقم القياسي للأسعار للسنة أو الفترة السابقة ) × 100.",
        unit: "نسبة مئوية",
        references: "المرصد الحضري الوطني (NUO)",
        dataSource: "الرقم القياسي لأسعار المستهلك -الهيئة العامة للإحصاء (يونيو 2020م - يونيو 2025م)",
        dataSourceType: "بيانات متاحة",
        geographicalScope: "منطقة",
        productionStatus: "تم الإنتاج",
        rating: "☆☆☆☆☆",
        notes: "",
        englishName: "Inflation rate",
        sector: "التنمية الإقتصادية"
    },
    {
        code: "EC-06",
        name: "متوسط دخل الأسرة",
        definition: "يشتمل متوسط دخل الأسرة على الدخل المكتسب من قبل الأسرة المتوسطة في المدينة. يتم حسابه عن طريق تقسيم الدخل المتاح لجميع الأسر (وفقًا لاستطلاعات الأسر) على عدد الأسر في المدينة.",
        calculationMethod: "متوسط دخل الأسرة (Average Household Income) = مجموع دخول جميع الأسر / إجمالي عدد الأسر.",
        unit: "ريال",
        references: "إطار الرصد الحضري (UMF)",
        dataSource: "مسح الدخل و الإنفاق الإستهلاكي للأسرة 2023 - الهيئة العامة للإحصاء",
        dataSourceType: "بيانات متاحة",
        geographicalScope: "منطقة",
        productionStatus: "تم الإنتاج",
        rating: "☆☆☆☆☆",
        notes: "",
        englishName: "average family income",
        sector: "التنمية الإقتصادية"
    },
    {
        code: "EC-13",
        name: "التوزيع النسبي لعدد رؤوس الأغنام والماعز",
        definition: "يعبر هذا المؤشر عن عدد رؤوس الأغنام والماعز التي تتوفر بمنطقة جازان",
        calculationMethod: "إجمالي عدد رؤوس الأغنام والماعز بالمنطقة / إجمالي المملكة*100",
        unit: "نسبة مئوية",
        references: "وزارة الاقتصاد والتخطيط (MEP)",
        dataSource: "الهيئة العامة للإحصاء - إحصاءات الثروة الحيوانية - المسح الزراعي الشامل لعام 2023م",
        dataSourceType: "بيانات متاحة",
        geographicalScope: "منطقة",
        productionStatus: "تم الإنتاج",
        rating: "☆☆☆☆☆",
        notes: "",
        englishName: "The relative distribution of the number of sheep and goats",
        sector: "التنمية الإقتصادية"
    },
    {
        code: "EC-15",
        name: "عدد المنشآت الصغيرة والمتوسطة",
        definition: "تعد متوسطة إذا تراوح عدد موظفيها بين (50- 250) موظفاً أو بلغت إيراداتها ما بين (40- 200) مليون. الصغيرة فهي التي يقل عدد موظفيها عن 50 موظفاً وتبلغ إيراداتها 40 مليوناً فأقل",
        calculationMethod: "إجمالي عدد المنشآت الصغيرة والمتوسطة / إجمالي المنشآت * 100",
        unit: "نسبة مئوية",
        references: "وزارة الاقتصاد والتخطيط (MEP)",
        dataSource: "الهيئة العامة للمنشآت الصغيرة والمتوسطة للربع الأول 2021م -2023م",
        dataSourceType: "بيانات متاحة",
        geographicalScope: "منطقة",
        productionStatus: "يحتاج إلى مراجعة / عليه ملاحظات",
        rating: "☆☆☆☆☆",
        notes: "اسم المؤشر في القاعدة غير مطابق لاسم المؤشر الذي تم انتاجه",
        englishName: "Number of small and medium enterprises",
        sector: "التنمية الإقتصادية"
    },
    {
        code: "EC-17",
        name: "نسبة التغير في الرقم القياسي العام لأسعار المستهلك حسب المدن الرئيسية",
        definition: "يوضح المؤشر نسبة التغير في الرقم القياسي العام لأسعار المستهلك حسب مدن المملكة الرئيسية",
        calculationMethod: "(الرقم القياسي العام لأسعار المستهلك في السنة اللاحقة - الرقم القياسي العام لأسعار المستهلك في السنة السابقة) /الرقم القياسي العام لأسعار المستهلك في السنة السابقة *100",
        unit: "نسبة مئوية",
        references: "وزارة الاقتصاد والتخطيط (MEP)",
        dataSource: "الرقم القياسي لأسعار المستهلك -الهيئة العامة للإحصاء (يونيو 2025م)",
        dataSourceType: "بيانات متاحة",
        geographicalScope: "منطقة",
        productionStatus: "يحتاج إلى مراجعة / عليه ملاحظات",
        rating: "☆☆☆☆☆",
        notes: "تحتاج إلى إضافة البيانات الخام في ورقة البيانات المتاحة، وكذلك إضافة المعالجة التي تمت لإنتاج المؤشر",
        englishName: "Percentage change in the overall consumer price index by major city",
        sector: "التنمية الإقتصادية"
    },
    {
        code: "EC-19",
        name: "التوزيع النسبي لكمية إنتاج أزهار القطف المزروعة",
        definition: "يعبر المؤشر عن نسبة كمية الإنتاج أزهار القطف المزروعة بمناطق المملكة",
        calculationMethod: "كمية الإنتاج أزهار القطف المزروعة / إجمالي المملكة *100",
        unit: "نسبة مئوية",
        references: "وزارة الاقتصاد والتخطيط (MEP)",
        dataSource: "المسح الزراعي الشامل 2023م- الهيئة العامة للإحصاء",
        dataSourceType: "بيانات متاحة",
        geographicalScope: "منطقة",
        productionStatus: "تم الإنتاج",
        rating: "☆☆☆☆☆",
        notes: "",
        englishName: "The relative distribution of the quantity of cut flower production cultivated",
        sector: "التنمية الإقتصادية"
    },
    {
        code: "EC-20",
        name: "التوزيع النسبي للمساحة المزروعة بأزهار القطف",
        definition: "يعبر المؤشر عن التوزيع النسبي لمساحة البيوت المحمية المزروعة بأزهار القطف حسب المحافظة/المنطقة",
        calculationMethod: "إجمالي المساحة المزروعة بأزهار القطف (فدان) /إجمالي مساحة البيوت المحمية (فدان) *100",
        unit: "نسبة مئوية",
        references: "وزارة الاقتصاد والتخطيط (MEP)",
        dataSource: "المسح الزراعي الشامل 2023م- الهيئة العامة للإحصاء",
        dataSourceType: "بيانات متاحة",
        geographicalScope: "منطقة",
        productionStatus: "تم الإنتاج",
        rating: "☆☆☆☆☆",
        notes: "",
        englishName: "Relative distribution of the area planted with cut flowers",
        sector: "التنمية الإقتصادية"
    },
    {
        code: "EC-21",
        name: "معدل انتاجية الفدان من الأعلاف (طن/فدان)",
        definition: "يقيس المؤشر إنتاجية الفدان من محاصيل الأعلاف",
        calculationMethod: "كمية الإنتاج من الأعلاف (طن) / إجمالي المساحة المزروعة بالأعلاف (فدان)",
        unit: "(طن/فدان)",
        references: "وزارة الاقتصاد والتخطيط (MEP)",
        dataSource: "المسح الزراعي الشامل 2023م- الهيئة العامة للإحصاء",
        dataSourceType: "بيانات متاحة",
        geographicalScope: "منطقة",
        productionStatus: "تم الإنتاج",
        rating: "☆☆☆☆☆",
        notes: "",
        englishName: "Feed yield per acre (tons/acre)",
        sector: "التنمية الإقتصادية"
    },
    {
        code: "EC-22",
        name: "انتاجية الفدان من محاصيل الحبوب (طن/فدان)",
        definition: "يقيس المؤشر إنتاجية الفدان من محاصيل الحبوب",
        calculationMethod: "كمية الإنتاج من محاصيل الحبوب (طن) / إجمالي المساحة المزروعة بمحاصيل الحبوب (فدان)",
        unit: "(طن/فدان)",
        references: "وزارة الاقتصاد والتخطيط (MEP)",
        dataSource: "المسح الزراعي الشامل 2023م- الهيئة العامة للإحصاء",
        dataSourceType: "بيانات متاحة",
        geographicalScope: "منطقة",
        productionStatus: "تم الإنتاج",
        rating: "☆☆☆☆☆",
        notes: "",
        englishName: "Grain crop yield per acre (tons/acre)",
        sector: "التنمية الإقتصادية"
    },
    {
        code: "EC-23",
        name: "التوزيع النسبي للمساحة المزروعة بمحصول الخضروات المكشوفة (الصيفية)",
        definition: "يعبر المؤشر التوزيع النسبي للمساحة المزروعة بمحصول الخضروات المكشوفة (الصيفية) بالمنطقة الي اجمالي المملكة",
        calculationMethod: "إجمالي المساحة المزروعة بمحصول الخضروات الصيفية (يالمنطقة) / إجمالي المساحة المزروعة بمحصول الخضروات الصيفية (بالمملكة)* 100",
        unit: "نسبة مئوية",
        references: "وزارة الاقتصاد والتخطيط (MEP)",
        dataSource: "المسح الزراعي الشامل 2023م- الهيئة العامة للإحصاء",
        dataSourceType: "بيانات متاحة",
        geographicalScope: "منطقة",
        productionStatus: "تم الإنتاج",
        rating: "☆☆☆☆☆",
        notes: "",
        englishName: "The relative distribution of the area cultivated with open-field (summer) vegetable crops",
        sector: "التنمية الإقتصادية"
    },
    {
        code: "EC-24",
        name: "انتاجية الفدان من محصول الخضروات المكشوفة (الصيفية) (طن/فدان)",
        definition: "يقيس المؤشر إنتاجية الفدان من محصول الخضروات المكشوفة (الصيفية)",
        calculationMethod: "إجمالي كمية الإنتاج من محصول الخضروات المكشوفة (الصيفية) (طن) / إجمالي المساحة المزروعة بمحصول الخضروات المكشوفة (الصيفية) (فدان)",
        unit: "(طن/فдан)",
        references: "وزارة الاقتصاد والتخطيط (MEP)",
        dataSource: "المسح الزراعي الشامل 2023م- الهيئة العامة للإحصاء",
        dataSourceType: "بيانات متاحة",
        geographicalScope: "منطقة",
        productionStatus: "تم الإنتاج",
        rating: "☆☆☆☆☆",
        notes: "",
        englishName: "Yield per acre of open-field (summer) vegetable crop (tons/acre)",
        sector: "التنمية الإقتصادية"
    },
    {
        code: "EC-25",
        name: "إنتاجية الفدان من محاصيل الحبوب والأعلاف (طن/فدان)",
        definition: "تعتبر الحبوب العلفية المنتجةمن المنتجات غذائية ثانوية تعتمد عليها صناعة الأعلاف بأكملها في تغذية الماشية والحيوانات المستأنسة.",
        calculationMethod: "إجمالي عدد المحاصيل الحبوب والاعلاف بالطن / إجمالي المساحة المزروعة بمحاصيل الحبوب والاعلاف بالفدان",
        unit: "(طن/فدان)",
        references: "وزارة الاقتصاد والتخطيط (MEP)",
        dataSource: "المسح الزراعي الشامل 2023م- الهيئة العامة للإحصاء",
        dataSourceType: "بيانات متاحة",
        geographicalScope: "منطقة",
        productionStatus: "تم الإنتاج",
        rating: "☆☆☆☆☆",
        notes: "",
        englishName: "Yield per acre of grain and fodder crops (tons/acre)",
        sector: "التنمية الإقتصادية"
    },
    {
        code: "EC-31",
        name: "تكلفة المعيشة",
        definition: "تشير تكلفة المعيشة إلى المبلغ اللازم لتغطية الضروريات الأساسية، كالسكن والغذاء والضرائب والرعاية الصحية، .... ألخ بمنطقة جازان، في سنة معينة",
        calculationMethod: "تحدد معظم المؤشرات تكلفة المعيشة الأساسية، والتي غالبًا ما يتم تمثيلها بـ 100",
        unit: "نسبة مئوية",
        references: "المجلس العالمي لبيانات المدن (WCCD)",
        dataSource: "مسح الدخل و الإنفاق الإستهلاكي للأسرة 2023 - الهيئة العامة للإحصاء",
        dataSourceType: "بيانات متاحة",
        geographicalScope: "منطقة",
        productionStatus: "يحتاج إلى مراجعة / عليه ملاحظات",
        rating: "☆☆☆☆☆",
        notes: "يجتاج إلى مراجعة لأن اسم المؤشر لا يتطابق مع ما تم انتاجه، وكذلك لا يتطابق مع تعريف المؤشر أو وحدة قياسه",
        englishName: "Cost of living",
        sector: "التنمية الإقتصادية"
    },
    {
        code: "EC-35",
        name: "نسبة التغير في الإنفاق على الخدمات الترفيهية والثقافية بمدن المملكة",
        definition: "يعبر المؤشر عن نسبة الزيادة او النقصان في إنفاق الأسرة السنوي على الخدمات الترفيهية والثقافية",
        calculationMethod: "(قيمة إنفاق الأسرة السنوي علي الخدمات الترفيهية والثقافية في السنة اللاحقة - قيمة إنفاق الأسرة السنوي علي الخدمات الترفيهية والثقافية في السنة السابقة) / قيمة إنفاق الأسرة السنوي علي الخدمات الترفيهية والثقافية في السنة السابقة) * 100",
        unit: "نسبة مئوية",
        references: "جودة الحياة (QoL)",
        dataSource: "الرقم القياسي لأسعار المستهلك -الهيئة العامة للإحصاء (يونيو 2025م)",
        dataSourceType: "بيانات متاحة",
        geographicalScope: "منطقة",
        productionStatus: "تم الإنتاج",
        rating: "☆☆☆☆☆",
        notes: "",
        englishName: "Percentage change in spending on recreational and cultural services in the cities of the Kingdom",
        sector: "التنمية الإقتصادية"
    },
    {
        code: "EC-39",
        name: "التوزيع النسبي للمساحة المحصودة من الأعلاف",
        definition: "يعبر المؤشر عن التوزيع النسبي للمساحة المحصودة من الأعلاف حسب المحافظة/المنطقة",
        calculationMethod: "إجمالي المساحة المحصودة من الأعلاف (فدان) / إجمالي المساحة * 100",
        unit: "نسبة مئوية",
        references: "وزارة الاقتصاد والتخطيط (MEP)",
        dataSource: "المسح الزراعي الشامل 2023م- الهيئة العامة للإحصاء",
        dataSourceType: "بيانات متاحة",
        geographicalScope: "منطقة",
        productionStatus: "تم الإنتاج",
        rating: "☆☆☆☆☆",
        notes: "",
        englishName: "Relative distribution of harvested fodder area",
        sector: "التنمية الإقتصادية"
    },
    {
        code: "EC-40",
        name: "التوزيع النسبي للمساحة المزروعة بمحاصيل الحبوب",
        definition: "يعبر المؤشر عن التوزيع النسبي للمساحة المزروعة بمحاصيل الحبوب حسب المحافظة/المنطقة",
        calculationMethod: "إجمالي المساحة المزروعة بمحاصيل الحبوب (فدان) / إجمالي المساحة (فدان)*100",
        unit: "نسبة مئوية",
        references: "وزارة الاقتصاد والتخطيط (MEP)",
        dataSource: "المسح الزراعي الشامل 2023م- الهيئة العامة للإحصاء",
        dataSourceType: "بيانات متاحة",
        geographicalScope: "منطقة",
        productionStatus: "تم الإنتاج",
        rating: "☆☆☆☆☆",
        notes: "",
        englishName: "Relative distribution of the area cultivated with grain crops",
        sector: "التنمية الإقتصادية"
    },
    {
        code: "EC-41",
        name: "نسبة المساحة التي لم يتم حصدها من المساحة المزروعة بمحصولات الحبوب",
        definition: "يعبر المؤشر عن نسبة المساحة التي لم يتم حصدها من المساحة المزروعة بمحصولات الحبوب",
        calculationMethod: "إجمالي المساحة التي لم يتم حصدها المزروعة بمحاصيل الحبوب (فدان) / إجمالي المساحة المزروعة بمحاصيل الحبوب (فدان) مضروباً في 100",
        unit: "نسبة مئوية",
        references: "وزارة الاقتصاد والتخطيط (MEP)",
        dataSource: "المسح الزراعي الشامل 2023م- الهيئة العامة للإحصاء",
        dataSourceType: "بيانات متاحة",
        geographicalScope: "منطقة",
        productionStatus: "تم الإنتاج",
        rating: "☆☆☆☆☆",
        notes: "",
        englishName: "Percentage of unharvested land from the area planted with grain crops",
        sector: "التنمية الإقتصادية"
    },
    {
        code: "EC-42",
        name: "التوزيع النسبي لإنتاج البيض (بالطن)",
        definition: "يعبر هذا المؤشر عن الكمية المنتجة من البيض بالطن",
        calculationMethod: "إجمالي إنتاج البيض (طن) بالمنطقة / إجمالي المملكة * 100",
        unit: "نسبة مئوية",
        references: "وزارة الاقتصاد والتخطيط (MEP)",
        dataSource: "الهيئة العامة للإحصاء - إحصاءات الثروة الحيوانية - المسح الزراعي الشامل لعام 2023م",
        dataSourceType: "بيانات متاحة",
        geographicalScope: "منطقة",
        productionStatus: "تم الإنتاج",
        rating: "☆☆☆☆☆",
        notes: "",
        englishName: "Relative distribution of egg production (in tons)",
        sector: "التنمية الإقتصادية"
    },
    {
        code: "EC-43",
        name: "حجم الصيد السمكي (بالطن)",
        definition: "يعبر هذا المؤشر عن الكمية المنتجة من السمك بالطن",
        calculationMethod: "إجمالي إنتاجية السمك (طن) بالمنطقة / إجمالي المملكة * 100",
        unit: "نسبة مئوية",
        references: "وزارة الاقتصاد والتخطيط (MEP)",
        dataSource: "إحصاءات الصيد البحري وتربية المائيات - الهيئة العامة للإحصاء 2024م",
        dataSourceType: "بيانات متاحة",
        geographicalScope: "منطقة",
        productionStatus: "تم الإنتاج",
        rating: "☆☆☆☆☆",
        notes: "",
        englishName: "Fish catch volume (in tons)",
        sector: "التنمية الإقتصادية"
    },
    {
        code: "EC-44",
        name: "نسبة التغير في عدد المنشآت الكبيرة",
        definition: "المنشأة تصنف كبيرة إذا زاد عدد موظفيها على 250 موظفاً أو تجاوزت إيراداتها 200 مليون ريال",
        calculationMethod: "إجمالي عدد المنشآت الكبيرة / إجمالي المنشآت * 100",
        unit: "نسبة مئوية",
        references: "وزارة الاقتصاد والتخطيط (MEP)",
        dataSource: "الهيئة العامة للمنشآت الصغيرة والمتوسطة للربع الأول 2021م -2023م",
        dataSourceType: "بيانات متاحة",
        geographicalScope: "منطقة",
        productionStatus: "يحتاج إلى مراجعة / عليه ملاحظات",
        rating: "☆☆☆☆☆",
        notes: "مصدر البيانات يحتاج إلى مراجعة لأن المصدر المذكور هو الهيئة العامة للمنشآت الصغيرة والمتوسطة والمؤشر يتحدث عن المنشآت الكبيرة",
        englishName: "Percentage change in the number of large establishments",
        sector: "التنمية الإقتصادية"
    },
    {
        code: "EC-45",
        name: "نسبة التغير في عدد المنشآت متناهية الصغر",
        definition: "تعتبر المنشأة المتناهية الصغر هي التي تضم عمالة من ١-٥ أو بمبيعات لا تزيد عن ٣ ملايين ريال.",
        calculationMethod: "إجمالي عدد المنشآت متناهية الصغر / إجمالي المنشآت * 100",
        unit: "نسبة مئوية",
        references: "وزارة الاقتصاد والتخطيط (MEP)",
        dataSource: "الهيئة العامة للمنشآت الصغيرة والمتوسطة للربع الأول 2021م -2023م",
        dataSourceType: "بيانات متاحة",
        geographicalScope: "منطقة",
        productionStatus: "تم الإنتاج",
        rating: "☆☆☆☆☆",
        notes: "",
        englishName: "Percentage change in the number of micro-enterprises",
        sector: "التنمية الإقتصادية"
    },
    {
        code: "EC-46",
        name: "عدد رؤوس الأبقار",
        definition: "يعبر هذا المؤشر عن عدد رؤوس الأبقار التي تتواجد بمنطقة جازان",
        calculationMethod: "إجمالي عدد رؤوس الأبقار بالمنطقة / إجمالي المملكة * 100",
        unit: "نسبة مئوية",
        references: "وزارة الاقتصاد والتخطيط (MEP)",
        dataSource: "الهيئة العامة للإحصاء - إحصاءات الثروة الحيوانية - المسح الزراعي الشامل لعام 2023م",
        dataSourceType: "بيانات متاحة",
        geographicalScope: "منطقة",
        productionStatus: "تم الإنتاج",
        rating: "☆☆☆☆☆",
        notes: "",
        englishName: "Number of cows",
        sector: "التنمية الإقتصادية"
    },
    {
        code: "EC-47",
        name: "التوزيع النسبي لعدد رؤوس الإبل",
        definition: "يعبر هذا المؤشر عن عدد رؤوس الأبل التي تتواجد بمنطقة جازان",
        calculationMethod: "إجمالي عدد رؤوس الأبل بالمنطقة / إجمالي المملكة * 100",
        unit: "نسبة مئوية",
        references: "وزارة الاقتصاد والتخطيط (MEP)",
        dataSource: "الهيئة العامة للإحصاء - إحصاءات الثروة الحيوانية - المسح الزراعي الشامل لعام 2023م",
        dataSourceType: "بيانات متاحة",
        geographicalScope: "منطقة",
        productionStatus: "تم الإنتاج",
        rating: "☆☆☆☆☆",
        notes: "",
        englishName: "Relative distribution of the number of camels",
        sector: "التنمية الإقتصادية"
    },
    {
        code: "EC-49",
        name: "التوزيع النسبي لعدد رؤوس الدجاج",
        definition: "يعبر هذا المؤشر عن عدد رؤوس الدجاج التي تمت تربيتها بمنطقة جازان",
        calculationMethod: "إجمالي عدد رؤوس الدجاج بالمنطقة / إجمالي المملكة * 100",
        unit: "نسبة مئوية",
        references: "وزارة الاقتصاد والتخطيط (MEP)",
        dataSource: "الهيئة العامة للإحصاء - إحصاءات الثروة الحيوانية - المسح الزراعي الشامل لعام 2023م",
        dataSourceType: "بيانات متاحة",
        geographicalScope: "منطقة",
        productionStatus: "تم الإنتاج",
        rating: "☆☆☆☆☆",
        notes: "",
        englishName: "The relative distribution of the number of chickens",
        sector: "التنمية الإقتصادية"
    },
    {
        code: "EC-50",
        name: "متوسط الإنفاق الاستهلاكي الشهري للأسرة حسب المنطقة الإدارية والجنسية لرئيس الأسرة",
        definition: "هو مؤشر يقيس متوسط الانفاق الاستهلاكي الشهري للأسر، وهو عبارة عن مجموع الانفاق الاستهلاكي الشهري للأسرة إلى إجمالي عدد الأسر .",
        calculationMethod: "(مجموع الانفاق الاستهلاكي الشهري للأسرة / اجمالي عدد الأسر)",
        unit: "ريال",
        references: "وزارة الاقتصاد والتخطيط (MEP)",
        dataSource: "مسح الدخل و الإنفاق الإستهلاكي للأسرة 2023 - الهيئة العامة للإحصاء",
        dataSourceType: "بيانات متاحة",
        geographicalScope: "منطقة",
        productionStatus: "تم الإنتاج",
        rating: "☆☆☆☆☆",
        notes: "",
        englishName: "Average monthly household consumption expenditure by administrative region and nationality of the head of household",
        sector: "التنمية الإقتصادية"
    },
    {
        code: "EC-51",
        name: "نسبة الإنفاق الاستهلاكي الشهري للأسرة إلى الدخل",
        definition: "يعبر المؤشر عن نسبة إنفاق الأسرة إلى الدخل كقيمة وسيطة بينهما( الدخل والإنفاق)",
        calculationMethod: "وسيط انفاق الأسرة / وسيط الدخل *100",
        unit: "نسبة مئوية",
        references: "وزارة الاقتصاد والتخطيط (MEP)",
        dataSource: "مسح الدخل و الإنفاق الإستهلاكي للأسرة 2023 - الهيئة العامة للإحصاء",
        dataSourceType: "بيانات متاحة",
        geographicalScope: "منطقة",
        productionStatus: "يحتاج إلى مراجعة / عليه ملاحظات",
        rating: "☆☆☆☆☆",
        notes: "اسم المؤشر على الرسمة البيانية يحتاج إلى تعديل ليكون مطابق لاسم المؤشر في جدول البيانات",
        englishName: "Ratio of monthly household consumption expenditure to income",
        sector: "التنمية الإقتصادية"
    },
    {
        code: "EC-52",
        name: "نسبة التغير في الإنفاق على الكهرباء والغاز وأنواع الوقود الأخرى بمدن المملكة",
        definition: "يعبر المؤشر عن نسبة الزيادة او النقصان في إنفاق الأسرة السنوي على الكهرباء والغاز وأنواع الوقود الأخرى",
        calculationMethod: "(قيمة إنفاق الأسرة السنوي علي الكهرباء والغاز وأنواع الوقود الأخرى في السنة اللاحقة - قيمة إنفاق الأسرة السنوي علي الكهرباء والغاز وأنواع الوقود الأخرى في السنة السابقة) / قيمة إنفاق الأسرة السنوي علي الكهرباء والغاز وأنواع الوقود الأخرى في السنة السابقة) * 100",
        unit: "نسبة مئوية",
        references: "وزارة الاقتصاد والتخطيط (MEP)",
        dataSource: "الرقم القياسي لأسعار المستهلك -الهيئة العامة للإحصاء (يونيو 2025م)",
        dataSourceType: "بيانات متاحة",
        geographicalScope: "منطقة",
        productionStatus: "تم الإنتاج",
        rating: "☆☆☆☆☆",
        notes: "",
        englishName: "Percentage change in spending on electricity, gas and other fuels in the cities of the Kingdom",
        sector: "التنمية الإقتصادية"
    },
    {
        code: "EC-53",
        name: "نسبة التغير في الإنفاق على إمدادات المياه والخدمات المتنوعة المتصلة بالمساكن بمدن المملكة",
        definition: "يعبر المؤشر عن نسبة الزيادة او النقصان في إنفاق الأسرة السنوي على إمدادات المياه والخدمات المتنوعة المتصلة بالمساكن",
        calculationMethod: "(قيمة إنفاق الأسرة السنوي علي إمدادات المياه والخدمات المتنوعة المتصلة بالمسكن في السنة اللاحقة - قيمة إنفاق الأسرة السنوي علي إمدادات المياه والخدمات المتنوعة المتصلة بالمسكن في السنة السابقة) / قيمة إنفاق الأسرة السنوي علي إمدادات المياه والخدمات المتنوعة المتصلة بالمسكن في السنة في السنة السابقة) * 100",
        unit: "نسبة مئوية",
        references: "وزارة الاقتصاد والتخطيط (MEP)",
        dataSource: "الرقم القياسي لأسعار المستهلك -الهيئة العامة للإحصاء (يونيو 2025م)",
        dataSourceType: "بيانات متاحة",
        geographicalScope: "منطقة",
        productionStatus: "تم الإنتاج",
        rating: "☆☆☆☆☆",
        notes: "",
        englishName: "Percentage change in spending on water supply and various housing-related services in the Kingdom's cities",
        sector: "التنمية الإقتصادية"
    },
    {
        code: "EC-54",
        name: "نسبة التغير في إنفاق الأسرة على التعليم قبل الابتدائي والتعليم الابتدائي بمدن المملكة",
        definition: "يعبر المؤشر عن نسبة الزيادة او النقصان في إنفاق الأسرة السنوي على التعليم الابتدائي (الرسوم ومصروفات الدروس الخاصة)",
        calculationMethod: "(قيمة إنفاق الأسرة السنوي علي التعليم الابتدائي في السنة اللاحقة - قيمة إنفاق الأسرة السنوي علي التعليم الابتدائي في السنة السابقة) / قيمة إنفاق الأسرة السنوي علي التعليم الابتدائي في السنة السابقة) * 100",
        unit: "نسبة مئوية",
        references: "وزارة الاقتصاد والتخطيط (MEP)",
        dataSource: "الرقم القياسي لأسعار المستهلك -الهيئة العامة للإحصاء (يونيو 2025م)",
        dataSourceType: "بيانات متاحة",
        geographicalScope: "منطقة",
        productionStatus: "تم الإنتاج",
        rating: "☆☆☆☆☆",
        notes: "",
        englishName: "Percentage change in household spending on pre-primary and primary education in the cities of the Kingdom",
        sector: "التنمية الإقتصادية"
    },
    {
        code: "EC-55",
        name: "نسبة التغير في إنفاق الأسرة على ايجار المسكن بمدن المملكة",
        definition: "يعبر المؤشر عن نسبة الزيادة او النقصان في إنفاق الأسرة السنوي على ايجار المسكن",
        calculationMethod: "(قيمة الانفاق السنوي علي ايجار المسكن في السنة اللاحقة - قيمة الانفاق السنوي علي ايجار المسكن في السنة السابقة) / قيمة الانفاق السنوي علي ايجار المسكن في السنة السابقة) * 100",
        unit: "نسبة مئوية",
        references: "وزارة الاقتصاد والتخطيط (MEP)",
        dataSource: "الرقم القياسي لأسعار المستهلك -الهيئة العامة للإحصاء (يونيو 2025م)",
        dataSourceType: "بيانات متاحة",
        geographicalScope: "منطقة",
        productionStatus: "تم الإنتاج",
        rating: "☆☆☆☆☆",
        notes: "",
        englishName: "Percentage change in household spending on housing rent in the cities of the Kingdom",
        sector: "التنمية الإقتصادية"
    },
    {
        code: "EC-56",
        name: "نصيب الفرد من الماشية المذبوحة",
        definition: "تعتبر مصدر رزق أساسي لكثير من العائلات، فهي توفر لهم دخلًا ثابتًا من خلال بيع اللحوم والألبان، بالإضافة إلى المنتجات الحيوانية الأخرى. في بعض المناطق، تعتمد الأسر الفقيرة بشكل كبير على هذا المصدر من الدخل",
        calculationMethod: "إجمالي عدد الماشية المذبوحة / إجمالي السكان",
        unit: "الماشية المذبوحة / فرد",
        references: "وزارة الاقتصاد والتخطيط (MEP)",
        dataSource: "الهيئة العامة للإحصاء - إحصاءات الثروة الحيوانية - المسح الزراعي الشامل لعام 2023م",
        dataSourceType: "بيانات متاحة",
        geographicalScope: "منطقة",
        productionStatus: "تم الإنتاج",
        rating: "☆☆☆☆☆",
        notes: "",
        englishName: "Per capita share of slaughtered livestock",
        sector: "التنمية الإقتصادية"
    },
    {
        code: "EC-62",
        name: "معدل عدد منشآت الأعمال لكل 100,000 نسمة",
        definition: "تشير منشآت الأعمال إلى الشركات أو المؤسسات. المؤسسة هي أصغر فئة من الوحدات الإعتبارية، أي أصغر وحدة تنظيمية تنتج سلعًا أو خدمات. وللحصول على بيانات عدد منشآت الأعمال، يتم الرجوع إلى السجل التجاري لمنشآت الأعمال.",
        calculationMethod: "(عدد منشآت الاعمال ÷ إجمالي عدد السكان) × 100,000",
        unit: "منشأة أعمال/100,000 نسمة",
        references: "المجلس العالمي لبيانات المدن (WCCD)",
        dataSource: "الهيئة العامة للمنشآت الصغيرة والمتوسطة للربع الأول 2021م -2023م",
        dataSourceType: "بيانات متاحة",
        geographicalScope: "منطقة",
        productionStatus: "تم الإنتاج",
        rating: "☆☆☆☆☆",
        notes: "",
        englishName: "Number of business establishments per 100,000 inhabitants",
        sector: "التنمية الإقتصادية"
    },
    {
        code: "EC-63",
        name: "نسبة الصيد السمكي من المصائد التقليدية في البحر الأحمر",
        definition: "نسبة كمية الأسماك المصادة من المصائد التقليدية في البحر الأحمر من إجمالي الصيد فيه.",
        calculationMethod: "(كمية الصيد التقليدي في البحر الأحمر / إجمالي الصيد في البحر الأحمر) × 100",
        unit: "نسبة مئوية",
        references: "منظمة الأغذية والزراعة (FAO)",
        dataSource: "إحصاءات الصيد البحري وتربية المائيات - الهيئة العامة للإحصاء 2024م",
        dataSourceType: "بيانات متاحة",
        geographicalScope: "منطقة",
        productionStatus: "يحتاج إلى مراجعة / عليه ملاحظات",
        rating: "☆☆☆☆☆",
        notes: "البيانات الأساسية لبطاقة تعريف المؤشر غير متوفرة",
        englishName: "Percentage of fish caught from traditional fisheries in the Red Sea",
        sector: "التنمية الإقتصادية"
    },
    {
        code: "EC-64",
        name: "نسبة التغير السنوي في كمية المصيد من المصائد التقليدية بالبحر الأحمر والخليج العربي",
        definition: "النسبة المئوية للتغير في كمية الصيد التقليدي بين سنة وأخرى.",
        calculationMethod: "[(كمية المصيد السنة الحالية - كمية المصيد السنة السابقة) / كمية المصيد السنة السابقة] × 100",
        unit: "نسبة مئوية",
        references: "منظمة الأغذية والزراعة (FAO)",
        dataSource: "إحصاءات الصيد البحري وتربية المائيات - الهيئة العامة للإحصاء 2024م",
        dataSourceType: "بيانات متاحة",
        geographicalScope: "منطقة",
        productionStatus: "يحتاج إلى مراجعة / عليه ملاحظات",
        rating: "☆☆☆☆☆",
        notes: "البيانات الأساسية لبطاقة تعريف المؤشر غير متوفرة",
        englishName: "Annual change in catch volume from traditional fisheries in the Red Sea and the Arabian Gulf",
        sector: "التنمية الإقتصادية"
    },
    {
        code: "EC-65",
        name: "التوزيع النسبي لأشجار النخيل",
        definition: "نسبة أشجار النخيل في منطقة محددة من إجمالي أشجار النخيل في منطقة أكبر.",
        calculationMethod: "(عدد أشجار النخيل في المنطقة المحددة / الإجمالي في المنطقة المرجعية) × 100",
        unit: "نسبة مئوية",
        references: "مؤشر محلي Local Indicator",
        dataSource: "المسح الزراعي الشامل 2023م- الهيئة العامة للإحصاء",
        dataSourceType: "بيانات متاحة",
        geographicalScope: "منطقة",
        productionStatus: "يحتاج إلى مراجعة / عليه ملاحظات",
        rating: "☆☆☆☆☆",
        notes: "البيانات الأساسية لبطاقة تعريف المؤشر غير متوفرة",
        englishName: "Relative distribution of palm trees",
        sector: "التنمية الإقتصادية"
    },
    {
        code: "EC-66",
        name: "نسبة أشجار النخيل والمثمر",
        definition: "نسبة أشجار النخيل والمثمرة من إجمالي عدد الأشجار في منطقة محددة.",
        calculationMethod: "(عدد أشجار النخيل والمثمرة / إجمالي عدد الأشجار) × 100",
        unit: "نسبة مئوية",
        references: "مؤشر محلي Local Indicator",
        dataSource: "المسح الزراعي الشامل 2023م- الهيئة العامة للإحصاء",
        dataSourceType: "بيانات متاحة",
        geographicalScope: "منطقة",
        productionStatus: "يحتاج إلى مراجعة / عليه ملاحظات",
        rating: "☆☆☆☆☆",
        notes: "البيانات الأساسية لبطاقة تعريف المؤشر غير متوفرة",
        englishName: "Percentage of palm and fruit trees",
        sector: "التنمية الإقتصادية"
    },
    {
        code: "EC-67",
        name: "نسبة التغير السنوي في عدد العمالة بالمصانع المنتجة",
        definition: "النسبة المئوية للتغير في عدد عمال المصانع بين نهاية سنة وأخرى.",
        calculationMethod: "[(عدد العمالة نهاية السنة الحالية - عدد العمالة نهاية السنة السابقة) / عدد العمالة نهاية السنة السابقة] × 100",
        unit: "نسبة مئوية",
        references: "منظمة العمل الدولية (ILO)",
        dataSource: "المركز الوطني للمعلومات الصناعية والتعدينة - نشرة التراخيص الصناعية 2023م",
        dataSourceType: "بيانات متاحة",
        geographicalScope: "منطقة",
        productionStatus: "يحتاج إلى مراجعة / عليه ملاحظات",
        rating: "☆☆☆☆☆",
        notes: "البيانات الأساسية لبطاقة تعريف المؤشر غير متوفرة",
        englishName: "Annual change in the number of workers in manufacturing plants",
        sector: "التنمية الإقتصادية"
    },
    {
        code: "EC-68",
        name: "نسبة التغير في الإنتاج بمشاريع الاستزراع السمكي بالمياه المالحة",
        definition: "النسبة المئوية للتغير في إنتاج الاستزراع السمكي في المياه المالحة بين عامين.",
        calculationMethod: "[(الإنتاج في سنة النهاية - الإنتاج في سنة البداية) / الإنتاج في سنة البداية] × 100",
        unit: "نسبة مئوية",
        references: "منظمة الأغذية والزراعة (FAO)",
        dataSource: "إحصاءات الصيد البحري وتربية المائيات - الهيئة العامة للإحصاء 2024م",
        dataSourceType: "بيانات متاحة",
        geographicalScope: "منطقة",
        productionStatus: "يحتاج إلى مراجعة / عليه ملاحظات",
        rating: "☆☆☆☆☆",
        notes: "البيانات الأساسية لبطاقة تعريف المؤشر غير متوفرة",
        englishName: "Percentage change in production in saltwater aquaculture projects",
        sector: "التنمية الإقتصادية"
    }
];